# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.create({user_id: 1, name:'阿部'})
User.create({user_id: 2, name:'鈴木'})
User.create({user_id: 3, name:'斉藤'})
User.create({user_id: 4, name:'加藤'})
User.create({user_id: 5, name:'斉藤'})
User.create({user_id: 6, name:'朝野'})
User.create({user_id: 7, name:'朝野'})
User.create({user_id: 8, name:'斉藤'})
User.create({user_id: 9, name:'山本'})
User.create({user_id: 10, name:'斉藤'})
User.create({user_id: 11, name:'朝野'})
User.create({user_id: 12, name:'山本'})
User.create({user_id: 13, name:'斉藤'})
User.create({user_id: 14, name:'鈴木'})
User.create({user_id: 15, name:'工藤'})
User.create({user_id: 16, name:'阿部'})
User.create({user_id: 17, name:'斉藤'})
User.create({user_id: 18, name:'朝野'})
User.create({user_id: 19, name:'斉藤'})
User.create({user_id: 20, name:'鈴木'})
User.create({user_id: 21, name:'工藤'})
User.create({user_id: 22, name:'加藤'})
User.create({user_id: 23, name:'斉藤'})
User.create({user_id: 24, name:'山本'})
User.create({user_id: 25, name:'佐藤'})
User.create({user_id: 26, name:'加藤'})
User.create({user_id: 27, name:'朝野'})
User.create({user_id: 28, name:'斉藤'})
User.create({user_id: 29, name:'阿部'})
User.create({user_id: 30, name:'山本'})
User.create({user_id: 31, name:'斉藤'})
User.create({user_id: 32, name:'朝野'})
User.create({user_id: 33, name:'斉藤'})
User.create({user_id: 34, name:'加藤'})
User.create({user_id: 35, name:'朝野'})
User.create({user_id: 36, name:'山本'})
User.create({user_id: 37, name:'斉藤'})
User.create({user_id: 38, name:'阿部'})
User.create({user_id: 39, name:'阿部'})
User.create({user_id: 40, name:'斉藤'})
User.create({user_id: 41, name:'鈴木'})
User.create({user_id: 42, name:'斉藤'})
User.create({user_id: 43, name:'工藤'})
User.create({user_id: 44, name:'鈴木'})
User.create({user_id: 45, name:'工藤'})
User.create({user_id: 46, name:'斉藤'})
User.create({user_id: 47, name:'山本'})
User.create({user_id: 48, name:'阿部'})
User.create({user_id: 49, name:'加藤'})
User.create({user_id: 50, name:'中出'})

Contest.create({id: 1, admin_id: 1, title:'第一回エンジニア合宿評価シート', detail:'評価してください', start_time:Time.now, end_time:Time.now + 1.hour})

# Product.create({id:1, contest_id:1, user_id: Random.new(50), title:"rails投票", detail:"頑張って作りました。", image:"https://dzwud19fd1isz.cloudfront.net/images/dog_img_miniature-dachshund.jpg", link:"https://www.min-inuzukan.com/"})
# Product.create({id:2, contest_id:1, user_id: Random.new(50), title:'rails投票', detail:'頑張って作りました。', image:'https://dzwud19fd1isz.cloudfront.net/images/dog_img_miniature-dachshund.jpg', link:'https://www.min-inuzukan.com/'})
# Product.create({id:3, contest_id:1, user_id: Random.new(50), title:'rails投票', detail:'頑張って作りました。', image:'https://dzwud19fd1isz.cloudfront.net/images/dog_img_miniature-dachshund.jpg', link:'https://www.min-inuzukan.com/'})
# Product.create({id:4, contest_id:1, user_id: Random.new(50), title:'rails投票', detail:'頑張って作りました。', image:'https://dzwud19fd1isz.cloudfront.net/images/dog_img_miniature-dachshund.jpg', link:'https://www.min-inuzukan.com/'})
# Product.create({id:5, contest_id:1, user_id: Random.new(50), title:'rails投票', detail:'頑張って作りました。', image:'https://dzwud19fd1isz.cloudfront.net/images/dog_img_miniature-dachshund.jpg', link:'https://www.min-inuzukan.com/'})
# Product.create({id:6, contest_id:1, user_id: Random.new(50), title:'rails投票', detail:'頑張って作りました。', image:'https://dzwud19fd1isz.cloudfront.net/images/dog_img_miniature-dachshund.jpg', link:'https://www.min-inuzukan.com/'})
# Product.create({id:7, contest_id:1, user_id: Random.new(50), title:'rails投票', detail:'頑張って作りました。', image:'https://dzwud19fd1isz.cloudfront.net/images/dog_img_miniature-dachshund.jpg', link:'https://www.min-inuzukan.com/'})
# Product.create({id:8, contest_id:1, user_id: Random.new(50), title:'rails投票', detail:'頑張って作りました。', image:'https://dzwud19fd1isz.cloudfront.net/images/dog_img_miniature-dachshund.jpg', link:'https://www.min-inuzukan.com/'})
# Product.create({id:9, contest_id:1, user_id: Random.new(50), title:'rails投票', detail:'頑張って作りました。', image:'https://dzwud19fd1isz.cloudfront.net/images/dog_img_miniature-dachshund.jpg', link:'https://www.min-inuzukan.com/'})
# Product.create({id:10, contest_id:1, user_id: Random.new(50), title:'rails投票', detail:'頑張って作りました。', image:'https://dzwud19fd1isz.cloudfront.net/images/dog_img_miniature-dachshund.jpg', link:'https://www.min-inuzukan.com/'})
# Product.create({id:11, contest_id:1, user_id: Random.new(50), title:'rails投票', detail:'頑張って作りました。', image:'https://dzwud19fd1isz.cloudfront.net/images/dog_img_miniature-dachshund.jpg', link:'https://www.min-inuzukan.com/'})
# Product.create({id:12, contest_id:1, user_id: Random.new(50), title:'rails投票', detail:'頑張って作りました。', image:'https://dzwud19fd1isz.cloudfront.net/images/dog_img_miniature-dachshund.jpg', link:'https://www.min-inuzukan.com/'})
# Product.create({id:13, contest_id:1, user_id: Random.new(50), title:'rails投票', detail:'頑張って作りました。', image:'https://dzwud19fd1isz.cloudfront.net/images/dog_img_miniature-dachshund.jpg', link:'https://www.min-inuzukan.com/'})
# Product.create({id:14, contest_id:1, user_id: Random.new(50), title:'rails投票', detail:'頑張って作りました。', image:'https://dzwud19fd1isz.cloudfront.net/images/dog_img_miniature-dachshund.jpg', link:'https://www.min-inuzukan.com/'})
# Product.create({id:15, contest_id:1, user_id: Random.new(50), title:'rails投票', detail:'頑張って作りました。', image:'https://dzwud19fd1isz.cloudfront.net/images/dog_img_miniature-dachshund.jpg', link:'https://www.min-inuzukan.com/'})
# Product.create({id:16, contest_id:1, user_id: Random.new(50), title:'rails投票', detail:'頑張って作りました。', image:'https://dzwud19fd1isz.cloudfront.net/images/dog_img_miniature-dachshund.jpg', link:'https://www.min-inuzukan.com/'})
# Product.create({id:17, contest_id:1, user_id: Random.new(50), title:'rails投票', detail:'頑張って作りました。', image:'https://dzwud19fd1isz.cloudfront.net/images/dog_img_miniature-dachshund.jpg', link:'https://www.min-inuzukan.com/'})
# Product.create({id:18, contest_id:1, user_id: Random.new(50), title:'rails投票', detail:'頑張って作りました。', image:'https://dzwud19fd1isz.cloudfront.net/images/dog_img_miniature-dachshund.jpg', link:'https://www.min-inuzukan.com/'})
# Product.create({id:19, contest_id:1, user_id: Random.new(50), title:'rails投票', detail:'頑張って作りました。', image:'https://dzwud19fd1isz.cloudfront.net/images/dog_img_miniature-dachshund.jpg', link:'https://www.min-inuzukan.com/'})
# Product.create({id:20, contest_id:1, user_id: Random.new(50), title:'rails投票', detail:'頑張って作りました。', image:'https://dzwud19fd1isz.cloudfront.net/images/dog_img_miniature-dachshund.jpg', link:'https://www.min-inuzukan.com/'})


